export enum StateCode {
  LOADING = 'LOADING',
  EMPTY = 'EMPTY',
  UNKNOWN = 'UNKNOWN',
  PARTIAL = 'PARTIAL',
  SUCCESS = 'SUCCESS',
  ERROR = 'ERROR',
  UNAUTHORIZED = 'UNAUTHORIZED',
  SESSION_EXPIRED = 'SESSION_EXPIRED',
  NETWORK_FAILURE = 'NETWORK_FAILURE',
  AI_FAILURE = 'AI_FAILURE',
  OCR_FAILURE = 'OCR_FAILURE',
  DATABASE_FAILURE = 'DATABASE_FAILURE',
  INSUFFICIENT_EVIDENCE = 'INSUFFICIENT_EVIDENCE'
}
